// Thin fetch handler: routing + CORS only. All logic lives in handlers.ts
// (and the pure modules it uses) so it can be tested with stubbed bindings.

import Anthropic from "@anthropic-ai/sdk";
// In production this is the real index generated by `npm run build:ask-index`
// (repo root) before deploy. At build/test time without CF credentials,
// scripts/ensure-index.mjs copies ask-index.sample.json here instead.
import askIndexJson from "../ask-index.json";
import type { AskIndex } from "./types";
import { createRateLimiter } from "./ratelimit";
import {
  handleAsk,
  handleFeedback,
  handleHealth,
  type AiBinding,
  type AnthropicLike,
  type DbBinding,
} from "./handlers";

export interface Env {
  AI: Ai;
  DB: D1Database;
  /** Set with: npx wrangler secret put ANTHROPIC_API_KEY */
  ANTHROPIC_API_KEY: string;
}

const askIndex = askIndexJson as AskIndex;

// Per-isolate state (best-effort rate limiting; see ratelimit.ts).
const limiter = createRateLimiter(10, 60_000);
let anthropic: Anthropic | undefined;

// CORS: the docs site's production domain is not fixed yet, so POSTs are
// allowed from any origin. Owner: once the domain is final, replace "*" with
// it (e.g. "https://dataverse-ops-mcp.pages.dev") to stop third-party sites
// from burning the question quota.
const CORS_HEADERS: Record<string, string> = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, POST, OPTIONS",
  "access-control-allow-headers": "content-type",
  "access-control-max-age": "86400",
};

function withCors(response: Response): Response {
  const out = new Response(response.body, response);
  for (const [key, value] of Object.entries(CORS_HEADERS)) out.headers.set(key, value);
  return out;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    const { pathname } = new URL(request.url);
    let response: Response;
    if (request.method === "GET" && pathname === "/v1/health") {
      response = handleHealth();
    } else if (request.method === "POST" && pathname === "/v1/ask") {
      anthropic ??= new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });
      response = await handleAsk(request, {
        ai: env.AI as unknown as AiBinding,
        db: env.DB as unknown as DbBinding,
        anthropic: anthropic as AnthropicLike,
        index: askIndex,
        limiter,
      });
    } else if (request.method === "POST" && pathname === "/v1/feedback") {
      response = await handleFeedback(request, { db: env.DB as unknown as DbBinding });
    } else {
      response = new Response(JSON.stringify({ error: "not_found" }), {
        status: 404,
        headers: { "content-type": "application/json" },
      });
    }
    return withCors(response);
  },
} satisfies ExportedHandler<Env>;
