/** One embedded documentation chunk from ask-index.json. */
export interface IndexChunk {
  id: string;
  /** URL path of the docs page, e.g. "/tools/get_plugin_traces/". */
  page: string;
  /** Page title + nearest heading. */
  title: string;
  text: string;
  vector: number[];
}

/** Shape of ask-index.json (generated by scripts/build-ask-index.mjs). */
export interface AskIndex {
  model: string;
  dims: number;
  chunks: IndexChunk[];
}
